language: objective-c
osx_image: xcode11
sudo: ture

cache:
  - bundler
  - cocoapods

before_install:
 - rvm use system
 - sudo gem install cocoapods -v '1.7.2'

script:
 - pod update

notifications:
email: false
